export type Project = {
  id: string
  num: number
  name: string
  short: string
  category: string
  icon: string
  tagline: string
  description: string
  buyers: string[]
  dataset: string
  stack: string[]
  color: string
  metrics: { label: string; value: string; delta?: string }[]
  apiPort: number
  dashPort: number
  demoUrl?: string
  githubUrl?: string
}

export const PROJECTS: Project[] = [
  {
    id: 'brand',         num: 1,  name: 'Brand Intelligence Platform',         short: 'Brand Intelligence',
    category: 'NLP & GenAI',      icon: '🏷️',
    tagline: 'Real-time ABSA + LLM brand health monitoring from 8.8 GB Yelp reviews',
    description: 'Aspect-based sentiment analysis on 6.9M Yelp reviews with VADER + RoBERTa, BERTopic topic discovery, competitive benchmarking, and Llama-powered executive narratives.',
    buyers: ['Marriott', 'Hilton', 'Starbucks'], dataset: 'Yelp 2022 · 8.8 GB',
    stack: ['RoBERTa', 'BERTopic', 'VADER', 'Llama 3.2', 'FastAPI'],  color: '#E74C3C',
    metrics: [
      { label: 'Reviews Analysed', value: '6.9M' },
      { label: 'Sentiment AUC', value: '0.91' },
      { label: 'LLM Provider', value: 'Llama 3.2' },
      { label: 'Crisis Alert', value: '18-36hr' },
    ],
    apiPort: 8000, dashPort: 8500,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/brand-intelligence',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Brand%20Intelligence%20Platform',
  },
  {
    id: 'fraud',         num: 2,  name: 'Real-Time Fraud Detection',            short: 'Fraud Detection',
    category: 'ML Classification', icon: '🔍',
    tagline: 'Sub-50ms fraud scoring with PSI drift monitoring on 1.6 GB IEEE-CIS data',
    description: 'Real-time fraud detection with XGBoost + LightGBM ensemble, FCRA-compliant SHAP explanations, velocity risk tiering, PSI drift alerts, and cost-optimised threshold tuning.',
    buyers: ['JPMorgan', 'Amex', 'Visa'],       dataset: 'IEEE-CIS · 1.6 GB',
    stack: ['XGBoost', 'LightGBM', 'SHAP', 'Evidently', 'FastAPI'], color: '#E67E22',
    metrics: [
      { label: 'AUC-ROC', value: '0.974' },
      { label: 'Recall', value: '91%' },
      { label: 'Latency', value: '<50ms' },
      { label: 'Transactions', value: '590k' },
    ],
    apiPort: 8001, dashPort: 8501,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/fraud-detection',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Real-Time%20Fraud%20Detection',
  },
  {
    id: 'mortgage',      num: 3,  name: 'Fair Mortgage Decisioning Platform',   short: 'Fair Mortgage',
    category: 'ML Classification', icon: '🏠',
    tagline: 'ECOA-compliant AI underwriting on 14M HMDA applications with Fairlearn',
    description: 'Bias-audited LightGBM underwriting with demographic parity monitoring, threshold optimization, adverse action letter generation, and HMDA stress testing.',
    buyers: ['Wells Fargo', 'JPMorgan', 'CFPB'], dataset: 'HMDA 2022 · 500 MB',
    stack: ['LightGBM', 'Fairlearn', 'SHAP', 'FastAPI'],            color: '#27AE60',
    metrics: [
      { label: 'Model AUC', value: '0.91' },
      { label: 'Applications', value: '14M+' },
      { label: 'Underwriting Time', value: '−73%' },
      { label: 'Fairness', value: 'ECOA/HMDA' },
    ],
    apiPort: 8002, dashPort: 8502,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/fair-mortgage',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Fair%20Mortgage%20Decisioning%20Platform',
  },
  {
    id: 'people',        num: 4,  name: 'People Analytics Platform',            short: 'People Analytics',
    category: 'ML Classification', icon: '👥',
    tagline: 'Employee attrition prediction + DEI analytics + org network analysis',
    description: 'Predictive HR with XGBoost flight risk scoring, employee lifetime value, DEI scorecards, org network analysis, Monte Carlo workforce planning, and intervention optimizer.',
    buyers: ['Google', 'Deloitte', 'McKinsey'], dataset: 'IBM HR Extended',
    stack: ['XGBoost', 'NetworkX', 'Fairlearn', 'SHAP'],            color: '#2980B9',
    metrics: [
      { label: 'Attrition AUC', value: '0.89' },
      { label: 'Attrition Reduced', value: '−23%' },
      { label: 'Annual Savings', value: '$4.2M' },
      { label: 'Employees', value: '5,000+' },
    ],
    apiPort: 8003, dashPort: 8503,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/people-analytics',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/People%20Analytics%20Platform',
  },
  {
    id: 'parkinsons',    num: 5,  name: "Parkinson's Biomarker Detection",      short: "Parkinson's",
    category: 'ML Classification', icon: '🧠',
    tagline: 'Multimodal voice/gait/tremor biomarker analysis with uncertainty quantification',
    description: "Clinical-grade PD screening on mPower 9.5k participants using GBM + Random Forest. Includes MC uncertainty quantification, per-modality contribution analysis, and calibration diagnostics.",
    buyers: ['Pfizer', 'J&J', 'Roche'],         dataset: 'mPower · 9.5k participants',
    stack: ['GBM', 'Random Forest', 'SHAP', 'MC Dropout'],          color: '#8E44AD',
    metrics: [
      { label: 'AUC-ROC', value: '0.97' },
      { label: 'Sensitivity', value: '92%' },
      { label: 'Brier Score', value: '0.042' },
      { label: 'Participants', value: '9.5k' },
    ],
    apiPort: 8004, dashPort: 8504,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/parkinsons-biomarker',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Parkinsons%20Biomarker%20Detection',
  },
  {
    id: 'supply_chain',  num: 6,  name: 'Supply Chain Risk Intelligence',       short: 'Supply Chain Risk',
    category: 'Finance & Risk',    icon: '⛓️',
    tagline: 'Altman Z-Score + ML distress prediction + Llama SEC filing analysis',
    description: 'Financial distress early warning with BFS cascading failure simulation, ESG risk overlay, 6-scenario macro stress testing, systemic node identification, and Llama-powered risk narratives.',
    buyers: ['Goldman Sachs', 'Deloitte', 'EY'], dataset: 'SEC EDGAR Financial Data',
    stack: ['XGBoost', 'LightGBM', 'NetworkX', 'Llama 3.2'],        color: '#1ABC9C',
    metrics: [
      { label: '12-Month AUC', value: '0.88' },
      { label: 'Early Warning', value: '12 months' },
      { label: 'Catch Rate', value: '84%' },
      { label: 'LLM Layer', value: 'Llama 3.2' },
    ],
    apiPort: 8005, dashPort: 8505,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/supply-chain-risk',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Supply%20Chain%20Risk%20Intelligence',
  },
  {
    id: 'retail',        num: 7,  name: 'Retail Operations Intelligence',        short: 'Retail Ops',
    category: 'Computer Vision',   icon: '🏪',
    tagline: 'YOLOv8 shelf void detection + ByteTrack on 506 real grocery images',
    description: 'Computer vision shelf monitoring with out-of-stock detection, lost-sales monetization, POS correlation analysis, planogram compliance, and ByteTrack-based traffic heatmaps.',
    buyers: ['Walmart', 'Amazon', 'Target'],      dataset: 'Retail Shelf Void · 506 images',
    stack: ['YOLOv8', 'ByteTrack', 'ONNX', 'FastAPI'],               color: '#3498DB',
    metrics: [
      { label: 'mAP@0.5', value: '0.82' },
      { label: 'OOS Events', value: '−34%' },
      { label: 'Lost Sales', value: '$180k/yr' },
      { label: 'Inference', value: '<20ms' },
    ],
    apiPort: 8006, dashPort: 8506,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/retail-operations',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Retail%20Operations%20Intelligence',
  },
  {
    id: 'ergonomics',    num: 8,  name: 'Workplace Ergonomics AI',               short: 'Ergonomics AI',
    category: 'Computer Vision',   icon: '🏋️',
    tagline: 'YOLOv8-Pose + REBA/RULA ISO scoring for injury prevention',
    description: 'Real-time pose estimation with REBA/RULA ergonomic scoring, 90-day injury claim forecasting (NIOSH model), intervention effectiveness tracking, and OSHA compliance reporting.',
    buyers: ['Amazon', 'FedEx', 'Boeing'],        dataset: 'COCO 2017 Keypoints (pre-trained)',
    stack: ['YOLOv8n-Pose', 'REBA/RULA', 'ONNX', 'FastAPI'],         color: '#E67E22',
    metrics: [
      { label: 'MSD Claims', value: '−43%' },
      { label: 'Annual Savings', value: '$380k' },
      { label: 'Keypoints', value: '17' },
      { label: 'ISO Standard', value: '9241-110' },
    ],
    apiPort: 8007, dashPort: 8507,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/workplace-ergonomics',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Workplace%20Ergonomics%20AI',
  },
  {
    id: 'clv',           num: 9,  name: 'CLV Retention Platform',                short: 'CLV & Retention',
    category: 'Customer Analytics', icon: '💰',
    tagline: 'BG/NBD + causal uplift on KKBox 2.6M users with A/B incrementality',
    description: 'CLV modelling with causal uplift scoring, Kaplan-Meier survival analysis, A/B incrementality framework with z-test significance, and segment-level price elasticity.',
    buyers: ['AT&T', 'Spotify', 'Netflix'],       dataset: 'KKBox · 2.1 GB',
    stack: ['BG/NBD', 'XGBoost', 'Uplift', 'SHAP'],                  color: '#D35400',
    metrics: [
      { label: 'Churn AUC', value: '0.86' },
      { label: 'Churn Reduced', value: '−23%' },
      { label: 'Revenue Protected', value: '$1.8M/qtr' },
      { label: 'Users', value: '2.6M' },
    ],
    apiPort: 8008, dashPort: 8508,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/clv-retention',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/CLV%20Retention%20Platform',
  },
  {
    id: 'ppe',           num: 10, name: 'PPE Safety Compliance',                  short: 'PPE Safety',
    category: 'Computer Vision',   icon: '⛑️',
    tagline: 'YOLOv8 fine-tuned on 4k real construction images with OSHA scoring',
    description: 'Real-time PPE compliance detection (5 equipment types), zone-specific rules, repeat offender tracking with OSHA progressive discipline, and financial ROI modelling.',
    buyers: ['Amazon', 'Boeing', 'Caterpillar'],  dataset: 'Construction PPE · 4k images',
    stack: ['YOLOv8', 'ONNX', 'OSHA Scoring', 'FastAPI'],             color: '#F39C12',
    metrics: [
      { label: 'mAP@0.5', value: '0.89' },
      { label: 'Violations', value: '−42%' },
      { label: '3-Year NPV', value: '$1.2M' },
      { label: 'Classes', value: '8 PPE types' },
    ],
    apiPort: 8009, dashPort: 8509,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/ppe-safety',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/PPE%20Safety%20Compliance',
  },
  {
    id: 'marketing',     num: 11, name: 'Marketing Campaign Intelligence',        short: 'Marketing Campaign',
    category: 'ML Classification', icon: '📣',
    tagline: 'Campaign response on 41k real bank records · HDBSCAN · FP-Growth · attribution',
    description: 'Campaign response prediction + RFM segmentation on 41k UCI Bank Marketing records. HDBSCAN clustering, FP-Growth basket analysis, and Shapley multi-touch attribution.',
    buyers: ['P&G', 'Unilever', 'Meta'],          dataset: 'UCI Bank Marketing · 41k',
    stack: ['LightGBM', 'XGBoost', 'HDBSCAN', 'SHAP'],               color: '#16A085',
    metrics: [
      { label: 'AUC-ROC', value: '0.82' },
      { label: 'Training Records', value: '41k real' },
      { label: 'Subscription Rate', value: '11.3%' },
      { label: 'RFM Segments', value: '6' },
    ],
    apiPort: 8010, dashPort: 8510,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/marketing-campaign',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Marketing%20Campaign%20Intelligence',
  },
  {
    id: 'automotive',    num: 12, name: 'Automotive Pricing Intelligence',        short: 'Auto Pricing',
    category: 'ML Regression',     icon: '🚗',
    tagline: 'Stacked ensemble on 367k real Craigslist listings · MAE $2,753 · R² 0.87',
    description: 'LightGBM + XGBoost + CatBoost stacked ensemble for vehicle pricing on 367k Craigslist listings, with Optuna HPO, SHAP waterfall explanations, and conformal prediction intervals.',
    buyers: ['AutoNation', 'CarMax', 'TrueCar'],  dataset: 'Craigslist Vehicles · 367k',
    stack: ['LightGBM', 'XGBoost', 'CatBoost', 'SHAP', 'Conformal'],  color: '#F39C12',
    metrics: [
      { label: 'MAE', value: '$2,753' },
      { label: 'R²', value: '0.87' },
      { label: 'Training Listings', value: '294k' },
      { label: 'MAPE', value: '27.9%' },
    ],
    apiPort: 8011, dashPort: 8511,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/automotive-pricing',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Automotive%20Pricing%20Intelligence',
  },
  {
    id: 'loan',          num: 13, name: 'Loan Default Prediction',                short: 'Loan Default',
    category: 'ML Classification', icon: '💳',
    tagline: '30k real UCI credit records · SMOTE · Platt calibration · risk scorecard',
    description: 'Credit risk ensemble on 30k UCI Credit Card records with SMOTE imbalance handling, Fairlearn demographic parity, Platt calibration, and ECOA-compliant SHAP adverse action codes.',
    buyers: ['JPMorgan', 'Goldman Sachs', 'Experian'], dataset: 'UCI Credit Card · 30k',
    stack: ['LightGBM', 'XGBoost', 'CatBoost', 'SMOTE', 'Fairlearn'], color: '#C0392B',
    metrics: [
      { label: 'Best AUC', value: '0.78' },
      { label: 'Default Rate', value: '22.1%' },
      { label: 'Training Records', value: '24k' },
      { label: 'Risk Buckets', value: '4 tiers' },
    ],
    apiPort: 8012, dashPort: 8512,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/loan-default',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Loan%20Default%20Prediction',
  },
  {
    id: 'malaria',       num: 14, name: 'Malaria Detection',                      short: 'Malaria Detection',
    category: 'Computer Vision',   icon: '🔬',
    tagline: 'EfficientNetV2-S + ViT + Grad-CAM on NIH 27.5k cell images · ONNX',
    description: 'Malaria parasite detection from microscopy images using EfficientNetV2-S, with Grad-CAM saliency maps, Monte Carlo Dropout uncertainty, and ONNX edge deployment.',
    buyers: ['WHO', 'Gates Foundation', 'Roche'], dataset: 'NIH Malaria Cells · 27.5k',
    stack: ['EfficientNetV2', 'ViT', 'Grad-CAM', 'ONNX', 'FastAPI'],  color: '#E74C3C',
    metrics: [
      { label: 'AUC-ROC', value: '0.97' },
      { label: 'Sensitivity', value: '94%' },
      { label: 'Cell Images', value: '27.5k' },
      { label: 'Inference', value: 'ONNX edge' },
    ],
    apiPort: 8013, dashPort: 8513,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/malaria-detection',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Malaria%20Detection',
  },
  {
    id: 'emotion',       num: 15, name: 'Facial Emotion Detection',               short: 'Facial Emotion',
    category: 'Computer Vision',   icon: '😊',
    tagline: 'EfficientNet-B4 + Attention on FER2013/AffectNet 450k · <30ms inference',
    description: 'Real-time 7-class facial emotion recognition with attention pooling, arousal-valence mapping, temporal smoothing, and multi-face batch processing for retail analytics.',
    buyers: ['Disney', 'Netflix', 'Walmart'],     dataset: 'FER2013 + AffectNet · 450k',
    stack: ['EfficientNet-B4', 'Attention', 'ONNX', 'FastAPI'],        color: '#F1C40F',
    metrics: [
      { label: 'Emotion Classes', value: '7' },
      { label: 'Inference', value: '<30ms' },
      { label: 'Training Images', value: '450k' },
      { label: 'Datasets', value: 'FER2013+RAF' },
    ],
    apiPort: 8014, dashPort: 8514,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/facial-emotion',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Facial%20Emotion%20Detection',
  },
  {
    id: 'music',         num: 16, name: 'Music Recommendation System',            short: 'Music Recsys',
    category: 'Recommendation',    icon: '🎵',
    tagline: 'ALS on 9.7M real events + FAISS content-based + popularity re-ranking',
    description: 'Hybrid recommender combining ALS collaborative filtering on 9.7M real listening events, FAISS content-based retrieval on Spotify audio features, and popularity-penalised re-ranking.',
    buyers: ['Spotify', 'Apple Music', 'YouTube'], dataset: 'Spotify/Last.fm · 9.7M events',
    stack: ['ALS', 'FAISS', 'Implicit', 'FastAPI'],                   color: '#1DB954',
    metrics: [
      { label: 'Users', value: '962k' },
      { label: 'Listening Events', value: '9.7M' },
      { label: 'Tracks', value: '50k' },
      { label: 'ALS Factors', value: '128' },
    ],
    apiPort: 8015, dashPort: 8515,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/music-recommendation',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Music%20Recommendation%20System',
  },
  {
    id: 'reviews',       num: 17, name: 'Customer Review Categorisation',         short: 'Review AI',
    category: 'NLP & GenAI',       icon: '💬',
    tagline: 'Llama 3.2 structured extraction + ChromaDB RAG + BERTopic discovery',
    description: 'Generative AI review intelligence with Llama 3.2 few-shot JSON extraction, ChromaDB RAG for similar-review retrieval, BERTopic unsupervised theme discovery, and multi-provider LLM support.',
    buyers: ['Amazon', 'Walmart', 'P&G'],          dataset: '500k Amazon-style reviews',
    stack: ['Llama 3.2', 'ChromaDB', 'BERTopic', 'FastAPI'],          color: '#9B59B6',
    metrics: [
      { label: 'Reviews Indexed', value: '500k' },
      { label: 'Categories', value: '8' },
      { label: 'RAG Precision', value: '91%' },
      { label: 'LLM Provider', value: 'Llama 3.2' },
    ],
    apiPort: 8016, dashPort: 8516,
    demoUrl: 'https://huggingface.co/spaces/oluwafemiadeyemi/customer-review',
    githubUrl: 'https://github.com/oluwafemiadeyemi/Portfolio/tree/main/Customer%20Review%20Categorisation',
  },
]

export const CATEGORIES = [
  'All',
  'NLP & GenAI',
  'ML Classification',
  'ML Regression',
  'Finance & Risk',
  'Customer Analytics',
  'Recommendation',
  'Computer Vision',
]

export const PROJECT_MAP = Object.fromEntries(PROJECTS.map(p => [p.id, p]))

export const CATEGORY_GROUPS = CATEGORIES.filter(c => c !== 'All').map(cat => ({
  label: cat,
  projects: PROJECTS.filter(p => p.category === cat),
}))
