"""
Central registry of all 17 portfolio projects.
Each entry drives the sidebar, home page cards, and per-project views.
"""

from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent  # Data Science Projects/

PROJECTS = [
    # ── NLP / Generative AI ─────────────────────────────────────────────
    {
        "id": "brand",
        "num": 1,
        "name": "Brand Intelligence Platform",
        "short": "Brand Intelligence",
        "category": "NLP & GenAI",
        "icon": "🏷️",
        "tagline": "Real-time ABSA + LLM brand health monitoring from Yelp reviews",
        "buyers": ["Marriott", "Hilton", "Starbucks"],
        "dataset": "Yelp 2022 · 8.8 GB",
        "stack": ["RoBERTa", "BERTopic", "VADER", "Llama 3.2"],
        "color": "#E74C3C",
        "path": BASE / "Brand Intelligence Platform",
        "api_port": 8000,
        "dash_port": 8500,
    },
    {
        "id": "reviews",
        "num": 17,
        "name": "Customer Review Categorisation",
        "short": "Review Categorisation",
        "category": "NLP & GenAI",
        "icon": "💬",
        "tagline": "Llama-powered review classification with RAG Q&A and VOC analytics",
        "buyers": ["Amazon", "Walmart", "P&G"],
        "dataset": "500k Amazon-style reviews",
        "stack": ["Llama 3.2:4k", "ChromaDB", "BERTopic", "Ollama"],
        "color": "#9B59B6",
        "path": BASE / "Customer Review Categorisation",
        "api_port": 8007,
        "dash_port": 8507,
    },
    # ── ML Classification ────────────────────────────────────────────────
    {
        "id": "fraud",
        "num": 2,
        "name": "Real-Time Fraud Detection",
        "short": "Fraud Detection",
        "category": "ML Classification",
        "icon": "🔍",
        "tagline": "590k transaction ensemble with real-time drift monitoring",
        "buyers": ["JPMorgan", "Amex", "Visa"],
        "dataset": "IEEE-CIS · 1.6 GB",
        "stack": ["XGBoost", "LightGBM", "Evidently", "SHAP"],
        "color": "#E67E22",
        "path": BASE / "Real-Time Fraud Detection",
        "api_port": 8001,
        "dash_port": 8501,
    },
    {
        "id": "mortgage",
        "num": 3,
        "name": "Fair Mortgage Decisioning",
        "short": "Fair Mortgage",
        "category": "ML Classification",
        "icon": "🏠",
        "tagline": "Bias-audited ML on 14M HMDA applications with Fairlearn",
        "buyers": ["Wells Fargo", "JPMorgan", "CFPB"],
        "dataset": "HMDA 2022 · 500 MB",
        "stack": ["LightGBM", "Fairlearn", "SHAP", "Platt Calibration"],
        "color": "#27AE60",
        "path": BASE / "Fair Mortgage Decisioning Platform",
        "api_port": 8002,
        "dash_port": 8502,
    },
    {
        "id": "loan",
        "num": 13,
        "name": "Loan Default Prediction",
        "short": "Loan Default",
        "category": "ML Classification",
        "icon": "💳",
        "tagline": "30k real credit records · SMOTE · Platt calibration · risk scorecard",
        "buyers": ["JPMorgan", "Goldman Sachs", "Experian"],
        "dataset": "UCI Credit Card · 30k records",
        "stack": ["LightGBM", "XGBoost", "CatBoost", "SMOTE", "Fairlearn"],
        "color": "#C0392B",
        "path": BASE / "Loan Default Prediction",
        "api_port": 8003,
        "dash_port": 8503,
    },
    {
        "id": "people",
        "num": 4,
        "name": "People Analytics Platform",
        "short": "People Analytics",
        "category": "ML Classification",
        "icon": "👥",
        "tagline": "Attrition prediction, DEI analytics, org network analysis",
        "buyers": ["Google", "Deloitte", "McKinsey"],
        "dataset": "IBM HR Extended · 5.8 MB",
        "stack": ["XGBoost", "NetworkX", "Fairlearn", "SHAP"],
        "color": "#2980B9",
        "path": BASE / "People Analytics Platform",
        "api_port": 8004,
        "dash_port": 8504,
    },
    {
        "id": "parkinsons",
        "num": 5,
        "name": "Parkinsons Biomarker Detection",
        "short": "Parkinsons Detection",
        "category": "ML Classification",
        "icon": "🧠",
        "tagline": "Multimodal biomarker fusion on mPower 9.5k participant dataset",
        "buyers": ["Pfizer", "J&J", "Roche"],
        "dataset": "mPower Telemonitoring · 9.5k",
        "stack": ["Random Forest", "XGBoost", "SHAP", "Multimodal Fusion"],
        "color": "#8E44AD",
        "path": BASE / "Parkinsons Biomarker Detection",
        "api_port": 8005,
        "dash_port": 8505,
    },
    {
        "id": "marketing",
        "num": 11,
        "name": "Marketing Campaign Intelligence",
        "short": "Marketing Campaign",
        "category": "ML Classification",
        "icon": "📣",
        "tagline": "Campaign response prediction on 41k real bank telemarketing records",
        "buyers": ["P&G", "Unilever", "Meta"],
        "dataset": "UCI Bank Marketing · 41k records",
        "stack": ["LightGBM", "XGBoost", "HDBSCAN", "SHAP"],
        "color": "#16A085",
        "path": BASE / "Marketing Campaign Intelligence",
        "api_port": 8006,
        "dash_port": 8506,
    },
    # ── ML Regression ────────────────────────────────────────────────────
    {
        "id": "automotive",
        "num": 12,
        "name": "Automotive Pricing Intelligence",
        "short": "Automotive Pricing",
        "category": "ML Regression",
        "icon": "🚗",
        "tagline": "367k real Craigslist listings · stacked ensemble · conformal intervals",
        "buyers": ["AutoNation", "CarMax", "TrueCar"],
        "dataset": "Craigslist Vehicles · 367k listings",
        "stack": ["LightGBM", "XGBoost", "CatBoost", "SHAP", "Conformal"],
        "color": "#F39C12",
        "path": BASE / "Automotive Pricing Intelligence",
        "api_port": 8007,
        "dash_port": 8507,
    },
    # ── Supply Chain / Finance ───────────────────────────────────────────
    {
        "id": "supply_chain",
        "num": 6,
        "name": "Supply Chain Risk Intelligence",
        "short": "Supply Chain Risk",
        "category": "Finance & Risk",
        "icon": "⛓️",
        "tagline": "Altman Z-score + ML distress prediction + Llama SEC filing analysis",
        "buyers": ["Goldman Sachs", "Deloitte", "EY"],
        "dataset": "SEC EDGAR Financial Distress",
        "stack": ["XGBoost", "LightGBM", "NetworkX", "Llama 3.2"],
        "color": "#1ABC9C",
        "path": BASE / "Supply Chain Risk Intelligence",
        "api_port": 8008,
        "dash_port": 8508,
    },
    # ── Customer Analytics ───────────────────────────────────────────────
    {
        "id": "clv",
        "num": 9,
        "name": "CLV Retention Platform",
        "short": "CLV & Retention",
        "category": "Customer Analytics",
        "icon": "💰",
        "tagline": "BG/NBD + causal uplift on KKBox 2.6M users",
        "buyers": ["AT&T", "Spotify", "Netflix"],
        "dataset": "KKBox · 2.1 GB",
        "stack": ["BG/NBD", "XGBoost", "Uplift Modelling", "SHAP"],
        "color": "#D35400",
        "path": BASE / "CLV Retention Platform",
        "api_port": 8009,
        "dash_port": 8509,
    },
    # ── Recommendation ───────────────────────────────────────────────────
    {
        "id": "music",
        "num": 16,
        "name": "Music Recommendation System",
        "short": "Music Recommendation",
        "category": "Recommendation",
        "icon": "🎵",
        "tagline": "ALS on 9.7M real events + FAISS content-based index",
        "buyers": ["Spotify", "Apple Music", "YouTube"],
        "dataset": "Spotify/Last.fm · 9.7M events",
        "stack": ["ALS", "FAISS", "Content-Based", "Implicit"],
        "color": "#1DB954",
        "path": BASE / "Music Recommendation System",
        "api_port": 8010,
        "dash_port": 8510,
    },
    # ── Computer Vision ──────────────────────────────────────────────────
    {
        "id": "malaria",
        "num": 14,
        "name": "Malaria Detection",
        "short": "Malaria Detection",
        "category": "Computer Vision",
        "icon": "🔬",
        "tagline": "EfficientNetV2-S + ViT + Grad-CAM on NIH 27.5k cell images",
        "buyers": ["WHO", "Gates Foundation", "Roche"],
        "dataset": "NIH Malaria Cells · 27.5k",
        "stack": ["EfficientNetV2", "ViT", "Grad-CAM", "ONNX"],
        "color": "#E74C3C",
        "path": BASE / "Malaria Detection",
        "api_port": 8011,
        "dash_port": 8511,
    },
    {
        "id": "emotion",
        "num": 15,
        "name": "Facial Emotion Detection",
        "short": "Facial Emotion",
        "category": "Computer Vision",
        "icon": "😊",
        "tagline": "EfficientNet-B4 + Attention on FER2013/AffectNet 450k images",
        "buyers": ["Disney", "Netflix", "Walmart"],
        "dataset": "FER2013 + AffectNet · 450k",
        "stack": ["EfficientNet-B4", "Attention Pooling", "Multi-task", "ONNX"],
        "color": "#F1C40F",
        "path": BASE / "Facial Emotion Detection",
        "api_port": 8012,
        "dash_port": 8512,
    },
    {
        "id": "retail",
        "num": 7,
        "name": "Retail Operations Intelligence",
        "short": "Retail Operations",
        "category": "Computer Vision",
        "icon": "🏪",
        "tagline": "YOLOv8 shelf void detection + ByteTrack on real grocery images",
        "buyers": ["Walmart", "Amazon", "Target"],
        "dataset": "Retail Shelf Void · 506 images",
        "stack": ["YOLOv8", "ByteTrack", "ONNX"],
        "color": "#3498DB",
        "path": BASE / "Retail Operations Intelligence",
        "api_port": 8013,
        "dash_port": 8513,
    },
    {
        "id": "ergonomics",
        "num": 8,
        "name": "Workplace Ergonomics AI",
        "short": "Ergonomics AI",
        "category": "Computer Vision",
        "icon": "🏋️",
        "tagline": "YOLOv8-Pose + REBA/RULA scoring for injury prevention",
        "buyers": ["Amazon", "FedEx", "Boeing"],
        "dataset": "COCO 2017 Keypoints (pre-trained)",
        "stack": ["YOLOv8n-Pose", "REBA/RULA", "ONNX", "FastAPI"],
        "color": "#E67E22",
        "path": BASE / "Workplace Ergonomics AI",
        "api_port": 8014,
        "dash_port": 8514,
    },
    {
        "id": "ppe",
        "num": 10,
        "name": "PPE Safety Compliance",
        "short": "PPE Safety",
        "category": "Computer Vision",
        "icon": "⛑️",
        "tagline": "YOLOv8 fine-tuned on 4k real construction PPE images + OSHA scoring",
        "buyers": ["Amazon", "Boeing", "Caterpillar"],
        "dataset": "Construction PPE · 4k images",
        "stack": ["YOLOv8", "OSHA Scoring", "ONNX"],
        "color": "#F39C12",
        "path": BASE / "PPE Safety Compliance",
        "api_port": 8015,
        "dash_port": 8515,
    },
]

CATEGORIES = ["NLP & GenAI", "ML Classification", "ML Regression",
               "Finance & Risk", "Customer Analytics", "Recommendation", "Computer Vision"]

PROJECT_BY_ID = {p["id"]: p for p in PROJECTS}
